RelativeSequence: Относительная последовательность
Before: До
After: После
NumberSign: №
Outflow: Отток
Inflow: Приток
Flow: Поток
Rule: Правило
Report: Отчет
Reports: Отчеты
Rules: Правила
LandPlotPurposeChange: Смена назначения ЗУ
GeneralPlanDocuments: Документы на ГенПлан
EveryJanuary: Каждый январь
Article: Статья
Periodicity: Периодичность
ConstructionArea: Площадь застройки
GenerateReport: Сформировать отчет
ReportsFixedName: Расчет (Смена ЗУ фикс)
Inflation: Инфляция
ReportParameters: Параметры отчета
Period: Период
Periods: Периоды
PleaseAddIfYouWish: Пожалуйста, добавьте, если хотите
NoDataYet: Данных пока нет
Project: Проект
Projects: Проекты
PasswordChanged: Пароль изменен
PasswordDoesNotMatch: Пароль не совпадает
RepeatPassword: Повторите пароль
UploadPhoto: Загрузить фото
PasswordChange: Смена пароля
TakePhoto: Сфотографироваться
DataAdministrator: Администратор данных
UserRoles: Роли пользователей
Overview: Обзор
Theme: Тема
UserAccount: Учетная запись пользователя
Profile: Профиль
SuperuserCannotBeDeleted: Суперпользователя нельзя удалить
Superuser: Суперпользователь
AnotherAccountAccessProhibited: Доступ к учетной записи другого пользователя запрещен
Time: Время
Events: События
Event: Событие
Next: Следующий
Previous: Предыдущий
Sun: вс
Sat: сб
Fri: пт
Thu: чт
Wed: ср
Tue: вт
Mon: пн
Calendar: Календарь
Stop: Остановить

IssueTracking: Отслеживание ошибок
Timeout: Тайм-аут
Find: Найти
Radius: Радиус
MainMenu: Главное меню
Type: Тип
Brand: Бренд
Phone: Телефон
OpeningHours: Часы работы
Address: Адрес
Search: Поиск
Landmark: Достопримечательность
Close: Закрыть
Tooltip: Подсказка
Duration: Продолжительность
EndDate: Дата окончания
StartDate: Дата начала
Chart: Диаграмма
Action: Действие
Timestamp: Временная метка
Hours: Часы
DurationHours: Продолжительность
Remarks: Замечания
StateMachineDiagram: Схема машины состояний
BasicEntities: Базовые сущности
NotAuthorized: Не разрешено
SignInToAccessPlease: Пожалуйста, войдите в систему, чтобы получить доступ к этой странице
LoginToAccessPlease: Пожалуйста, войдите в систему, чтобы получить доступ к этой странице
Statistics: Статистика
Owner: Владелец
Sequence: Последовательность
End: Конец
Start: Начало
LoginForMoreDetailsPlease: Пожалуйста, войдите в систему для более подробной информации
WelcomeTo: Добро пожаловать на
Location: Локация
ChangePassword: Изменить пароль
AlreadyExists: Уже существует
No: Нет
Yes: Да
DemoUserAccounts: Демо-аккаунты
User: Пользователь
Administrator: Администратор
InvalidUrlOrRemoved: Неверный URL-адрес или ресурс удален
Authentication: Аутентификация
Or: или
Back: Вернуться
BackToHomepage: Вернуться на домашнюю страницу
InvalidArguments: Неверные аргументы
PermissionDenied: Доступ запрещен
PageNotFound: Страница не найдена
PleaseAddIfNecessary: Пожалуйста, добавьте, если необходимо
Empty: Пустой
Copy: Копировать
Settings: Настройки
Country: Страна
CountryRU: Россия
CountryUS: США
Language: Язык
LangRu: Русский
LangEn: Английский
Create: Создать
Link: Ссылка
Attribution: Атрибуция
Logo: Логотип
Photo: Фото
Url: URL-адрес
Details: Подробности
Title: Название
RecordDeleted: Запись удалена
InvalidFormData: Неверные данные формы
DateCreated: Дата создания
TimeCreated: Время создания
Author: Автор
SourceCode: Исходный код
GitHub: GitHub
EntityRelationshipDiagram: Диаграмма взаимосвязи сущностей
Documentation: Документация
Description: Описание
Name: Имя
RecordEdited: Запись отредактирована
RecordAdded: Запись добавлена
Edit: Редактировать
DeleteAreYouSure: Вы уверены, что хотите удалить?
ConfirmPlease: Пожалуйста подтвердите
Actions: Действия
Homepage: Домашняя страница
MenuButton: Кнопка меню
Save: Сохранить
Cancel: Отмена
Dele: Удалить
Change: Изменить
Add: Добавить
NoData: Нет данных
NothingToShow: Нечего показывать
EmptyDataSet: Пустой набор данных
AccessDeniedAdminsOnly: Доступ к этой странице имеют только администраторы. Пожалуйста, войдите под учетной записью администратора
LoginPlease: Пожалуйста, войдите в систему
Users: Пользователи
Email: Электронная почта
ResetPassword: Сбросить пароль
RestoreLogin: Восстановить вход
Password: Пароль
Username: Логин
SignOut: Выйти
SignIn: Войти
Home: Главная
MetaDescription: Калькулятор ВНД
AppName: IRR Calc

Doc000: Калькулятор ВНД
Doc001 appname href: <a class="link" href=#{href} target=_blank>#{appname}</a> - Калькулятор ВНД.
Doc002 href: <a class="link" href=#{href} target=_blank>Репозиторий проекта</a> на GitHub.
Doc003 href: Обратите внимание, что приложение, работающее в данный момент, является демонстрационным. Любые действия разрешены и поощряются. <a class="link" href=#{href} target=_blank>Сообщайте об ошибках</a> на GitHub.
Doc004: Учетная запись суперпользователя определяется во время развертывания. Суперпользователь управляет другими пользователями и предоставляет или отзывает права администратора конкретным пользователям.
Doc005: Интеграция с внешними API
Doc006: Менеджер мероприятий может создавать мероприятия, отправлять уведомления, назначать участников только на те мероприятия, которыми он управляет.
Doc007: Администраторы данных имеют полный доступ ко всем данным.